version: "3.9"

services:
  db:
    image: postgres:14
    container_name: fifa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20030218
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  ingest:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fifa-ingest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 20030218
    command: ["python", "src/ingest_to_postgres.py"]
    restart: "no"

  task2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fifa-task2
    depends_on:
      ingest:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 20030218
    command: ["python", "src/analytics_spark.py"]
    restart: "no"

  task3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fifa-task3
    depends_on:
      task2:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 20030218
    command: ["python", "src/pytorch_ml.py"]
    restart: "no"

  task4:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fifa-task4
    depends_on:
      task3:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 20030218
    command: ["python", "src/spark_ml.py"]
    restart: "no"

